functional
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
implicit
  - необходима  возможность выбора любого из способов оплаты, но только одного (например, нельзя выбрать одновременно оплату онлайн и оплату наличными при доставке)
  - если пользователь выбирает оплату онлайн через специальные платежные сервисы, должен происходить переход на страницы эти сервисов для авторизации и продолжении процесса оплаты
  - должна быть возможность добавить номер мобильного телефона клиента для обратной связи
  - должна быть предусмотрена пагинация по страницам для общего списка товаров
  - товар добавляется в корзину и это очевидно для пользователя (есть уведомление и миникорзина пополняется выбранной позицией)
  - покупатель видит полную стоимость всей покупки
  - если товара нет на складе, то его нельзя добавить в корзину - и об этом появляется уведомление
  - изменение заказа (отмена, изменение количества)
